import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/Header";
import Sidebar from "@/components/ui/Sidebar"
import {ClerkProvider,SignInButton,SignedIn,SignedOut,UserButton} from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        
        >
          <Header />
          <div className="flex min-h-screen">
            <Sidebar/>
              <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
              {children}
              </div>
          </div>
          
        
      </body>
    </html>
    </ClerkProvider>
    
  );
}
